### ISSUE TITLE
Add Leetcode potd solution

### ISSUE THREAD

**Issue by Gyanthakur** [Gyanthakur/LeetCode_potd#1]

**Comment by yogeshhh1207** [comment]
> > _No description provided._
> 
> You can add the previous potd also which is not present in this repo

Soon!!

**Comment by Utkarsh-Aggarwal** [comment]
please assign this to  me my gfg profile https://www.geeksforgeeks.org/user/utkarshagbfsx/

**Comment by Utkarsh-Aggarwal** [comment]
my leetcode profile https://leetcode.com/problemset/

**Comment by Gyanthakur** [comment]
> @Gyanthakur assign me this as i am solving leetcode potd daily

add today's potd assigned to @harsh0728

**Comment by shimmer12** [comment]
@Gyanthakur  assign me this as i am solving leetcode potd daily, thank you !

**Comment by Gyanthakur** [comment]
> @Gyanthakur assign me this as i am solving leetcode potd daily, thank you !

Add today's potd assigned to @shimmer12

**Comment by shimmer12** [comment]
@Gyanthakur assign me i want to solve the potd

**Comment by TanishaBansal101** [comment]
@Gyanthakur assign me this as i am solving leetcode potd daily, thank you !

**Comment by Samruddhi345A** [comment]
Hi Please assign to me this task

**Comment by Gyanthakur** [comment]
> Hi Please assign to me this task

Assigned @Samruddhi345A

**Comment by kevinzb56** [comment]
@Gyanthakur assign me this task as I regularly solve potd.
