### ISSUE TITLE
Please add solution to 10th Oct 2024

### ISSUE THREAD

**Issue by prmehta09** [Gyanthakur/LeetCode_potd#35]
## 🐛 Bug Report (if applicable)

- **Steps to Reproduce:** 
  1. Step 1
  2. Step 2
  3. Step 3
- **Expected behavior:** What should happen?
- **Actual behavior:** What happened instead?
- **Environment (if applicable):**
  - Browser/OS: 
  - Device:

**Comment by coding-idea** [comment]
**everyone this repo and account, he is not following the values of hacktoberfest.
first learn the spelling of hacktoberfest.
you cant force people to follow your account for getting the PR merged.** 

<img width="355" alt="Screenshot 2024-10-19 at 7 49 46 PM" src="https://github.com/user-attachments/assets/3abee755-2fdd-486d-ab38-4b9a9bc2bdc8">
